org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
ANDROID_COMPILE_SDK=36
ANDROID_TARGET_SDK=36
ANDROID_MIN_SDK=24
ANDROID_BUILD_TOOLS=34.0.0
ANDROID_NDK_VERSION=26.3.11579264
ANDROID_CMAKE_VERSION=3.22.1
ANDROID_CMDLINE_TOOLS=9477386
ANDROID_ADDITIONAL_PLATFORMS=30,31,33,34,35
